# Production environment values
replicaCount: 3

image:
  repository: abelchesire/technical-interview
  tag: "1.0.0"
  pullPolicy: IfNotPresent

app:
  ginMode: release

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rate-limit: "100"
  hosts:
    - host: api.technical-interview.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: technical-interview-tls
      hosts:
        - api.technical-interview.com

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 20
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 75

postgresql:
  auth:
    password: "CHANGE-ME-IN-PRODUCTION"
  primary:
    persistence:
      enabled: true
      size: 50Gi
      storageClass: "fast-ssd"
    resources:
      limits:
        cpu: 2000m
        memory: 4Gi
      requests:
        cpu: 1000m
        memory: 2Gi
  readReplicas:
    replicaCount: 2
    persistence:
      enabled: true
      size: 50Gi
    resources:
      limits:
        cpu: 1000m
        memory: 2Gi
      requests:
        cpu: 500m
        memory: 1Gi

# IMPORTANT: Override these with actual secrets in production
secrets:
  dbPassword: "CHANGE-ME"
  oidcClientSecret: "CHANGE-ME"
  smsApiSecret: "CHANGE-ME"

config:
  environment: production

# Pod disruption budget for high availability
podDisruptionBudget:
  enabled: true
  minAvailable: 1

# Network policies for security
networkPolicy:
  enabled: true
  policyTypes:
    - Ingress
    - Egress